# Generated by Django 4.1.7 on 2023-03-02 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_productmodel_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_rename_orderedproduct_orderedproductmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderModel',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderedProductModel',
            new_name='OrderedProduct',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказавший пользователь'),
        ),
    ]
