# Generated by Django 4.1.7 on 2023-03-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='сategory',
            new_name='category',
        ),
    ]
