# Generated by Django 4.1.7 on 2023-03-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y-%m-%d', verbose_name='Картинки продукта'),
        ),
        migrations.DeleteModel(
            name='ProductImageModel',
        ),
    ]
